### ISSUE TITLE
Local Storage or only for web

### ISSUE THREAD

**Issue by shiyewuxian** [allou-deyforyou/surrealdb.dart#1]
Hi @allou-deyforyou  this is good.
Further I would like to have your advise that if this library is only for web query, or if we could use it for local storage like Isar.
Thanks.

**Comment by allou-deyforyou** [comment]
Hi @shiyewuxian,
It's my goal to add Surreal Embedded, but we're currently going to start with Web Query.
You can use it with Isar for now.

**Comment by shiyewuxian** [comment]
@allou-deyforyou 
Thanks. Looking forward to your amzing release.
